export const INITIAL_STATE = 'INITIAL_STATE';
export const SEARCH_EVENTS = 'SEARCH_EVENTS';
export const FETCH_EVENTS = 'FETCH_EVENTS';
export const EVENTS_READY = 'EVENTS_READY';
export const FILTER_EVENTS = 'FILTER_EVENTS';
export const FILTER_GENRES = 'FILTER_GENRES';
export const FILTER_TIMES = 'FILTER_TIMES';
